### ISSUE TITLE
Axolotl bitmap  logos for Arena - Chess GUI - WinBoard/XBoard Interface etc.

### ISSUE THREAD

**Issue by yellow-panther** [louism33/Axolotl#3]
Hello louism33,

jar-file works now!

cf. 
[Axolotl logos.zip](https://github.com/louism33/Axolotl/files/2580783/Axolotl.logos.zip)

a survey of chess GUIs with WB&UCI support cf. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list 

Ron from CCWiki http://computer-chess.org/doku.php?id=home  will add Axolotl here: 
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list

UCI-protocol description > http://download.shredderchess.com/div/uci.zip

Regards,

**Comment by louism33** [comment]
Hi yellow-panther,
Thanks again for your support and advice! I am grateful for the time you have given. Thank you also for the pictures of axolotls, they are very nice. I will certainly choose a logo soon!

Kind regards,

Louis
