### ISSUE TITLE
Axolotl and endgame tablebases (EGTBs)

### ISSUE THREAD

**Issue by yellow-panther** [louism33/Axolotl#8]
Hello louism33, which EGTBs are supported by your chess engine Axolotl?
cf. a survey here http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:egtbs_list

regards

**Comment by louism33** [comment]
Hi yellow-panther,

Good to hear from you again! Currently Axolotl does not support end game table bases, and does not have an opening book. This will be one of the first additions in v2. I hope this does not cause any problems for you, but please let me know if it does.
Thank you also for the (as always) extremely useful links - I will certainly incorporate this into the next version of my engine.

As always, please feel free to share your feedback,
Kind regards,
Louis
